const EPISODE_LIST_FETCH_REQUESTED = 'episodeList/requested';
const EPISODE_LIST_FETCH_SUCCEEDED = 'episodeList/succeeded';
const EPISODE_LIST_FETCH_FAILED = 'episodeList/failed';

export { EPISODE_LIST_FETCH_REQUESTED, EPISODE_LIST_FETCH_SUCCEEDED, EPISODE_LIST_FETCH_FAILED };
