const SHOW_FETCH_REQUESTED = 'show/requested';
const SHOW_FETCH_SUCCEEDED = 'show/succeeded';
const SHOW_FETCH_FAILED = 'show/failed';

const EPISODE_LIST_FETCH_REQUESTED = 'episodeList/requested';
const EPISODE_LIST_FETCH_SUCCEEDED = 'episodeList/succeeded';
const EPISODE_LIST_FETCH_FAILED = 'episodeList/failed';

export {
  EPISODE_LIST_FETCH_REQUESTED,
  EPISODE_LIST_FETCH_SUCCEEDED,
  EPISODE_LIST_FETCH_FAILED,
  SHOW_FETCH_REQUESTED,
  SHOW_FETCH_SUCCEEDED,
  SHOW_FETCH_FAILED,
};
